# Generated by Django 4.2.7 on 2026-03-25 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('husband_work_address', models.CharField(blank=True, default='', max_length=500)),
                ('wife_work_address', models.CharField(blank=True, default='', max_length=500)),
                ('has_children', models.BooleanField(default=False)),
                ('children_school_address', models.CharField(blank=True, default='', max_length=500)),
                ('children_kindergarten_address', models.CharField(blank=True, default='', max_length=500)),
                ('priority_transport', models.BooleanField(default=True, help_text='Важен транспорт')),
                ('priority_ecology', models.BooleanField(default=True, help_text='Важна экология')),
                ('priority_infrastructure', models.BooleanField(default=True, help_text='Важна инфраструктура')),
                ('priority_safety', models.BooleanField(default=True, help_text='Важна безопасность')),
                ('max_commute_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_family_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=1000)),
                ('source_type', models.CharField(choices=[('cian', 'Циан'), ('avito', 'Авито'), ('yandex', 'Яндекс.Недвижимость'), ('unknown', 'Неизвестно')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('district', models.CharField(blank=True, default='', max_length=200)),
                ('metro_station', models.CharField(blank=True, default='', max_length=200)),
                ('metro_distance_min', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('residential_complex', models.CharField(blank=True, default='', max_length=300)),
                ('rc_year_built', models.IntegerField(blank=True, null=True)),
                ('rc_developer', models.CharField(blank=True, default='', max_length=300)),
                ('rc_class', models.CharField(blank=True, default='', max_length=50)),
                ('rc_parking', models.BooleanField(default=False)),
                ('rc_concierge', models.BooleanField(default=False)),
                ('rc_playground', models.BooleanField(default=False)),
                ('rc_closed_territory', models.BooleanField(default=False)),
                ('rc_features', models.JSONField(blank=True, default=list)),
                ('score_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_transport', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_ecology', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_infrastructure', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_safety', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_price_quality', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_building', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_floor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score_district_perspective', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commute_husband_min', models.IntegerField(blank=True, null=True)),
                ('commute_wife_min', models.IntegerField(blank=True, null=True)),
                ('commute_school_min', models.IntegerField(blank=True, null=True)),
                ('commute_kindergarten_min', models.IntegerField(blank=True, null=True)),
                ('nearby_metro_stations', models.JSONField(blank=True, default=list)),
                ('nearby_schools', models.JSONField(blank=True, default=list)),
                ('nearby_kindergartens', models.JSONField(blank=True, default=list)),
                ('nearby_clinics', models.JSONField(blank=True, default=list)),
                ('nearby_shops', models.JSONField(blank=True, default=list)),
                ('nearby_parks', models.JSONField(blank=True, default=list)),
                ('district_avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('district_price_trend', models.CharField(blank=True, choices=[('rising', 'Растёт'), ('stable', 'Стабильно'), ('falling', 'Падает')], default='', max_length=20)),
                ('district_perspective', models.TextField(blank=True, default='')),
                ('advantages', models.JSONField(blank=True, default=list)),
                ('disadvantages', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('similar_apartments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('analyzing', 'Анализируется'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('family_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.familyprofile')),
            ],
            options={
                'db_table': 'analytics_apartment_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
