# Generated by Django 4.2.7 on 2026-03-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentanalysis',
            name='apartments_per_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='bathroom_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='building_series',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='building_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='bus_routes_nearby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='ceiling_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='district_crime_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='entrance_condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_balcony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_freight_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_garbage_chute',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_loggia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_mcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_mck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='has_passenger_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='near_airport_noise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='near_highway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='near_industrial_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='near_railway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='nearby_fitness',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='nearby_pharmacies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='noise_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='price_per_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='rc_dog_walking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='rc_sports_ground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='rc_underground_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='renovation_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='score_apartment_layout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='score_daily_comfort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='score_quietness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='score_social_infra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='window_view',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='has_car',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='has_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='priority_quietness',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='district_avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='district_price_trend',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_building',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_district_perspective',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_ecology',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_infrastructure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_price_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_safety',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apartmentanalysis',
            name='score_transport',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='priority_ecology',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='priority_infrastructure',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='priority_safety',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familyprofile',
            name='priority_transport',
            field=models.BooleanField(default=True),
        ),
    ]
