# Generated by Django 4.2.7 on 2026-03-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_apartmentanalysis_apartments_per_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentanalysis',
            name='explanations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='familyprofile',
            name='buyer_type',
            field=models.CharField(choices=[('single', 'Один человек'), ('couple', 'Пара'), ('family', 'Семья с детьми')], default='couple', max_length=20),
        ),
    ]
