# Generated by Django 4.2.7 on 2026-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_apartmentanalysis_explanations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentanalysis',
            name='kindergartens_total_in_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='nearby_malls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='schools_total_in_district',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
