# Generated by Django 4.2.7 on 2026-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_apartmentanalysis_kindergartens_total_in_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentanalysis',
            name='mkad_distance_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='nearby_highways',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='apartmentanalysis',
            name='nearby_metros',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
