# Generated by Django 4.2.7 on 2025-12-04 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cian', 'Циан'), ('avito', 'Авито'), ('yandex', 'Яндекс.Недвижимость')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершена'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('apartments_found', models.IntegerField(default=0)),
                ('apartments_new', models.IntegerField(default=0)),
                ('apartments_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'parse_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.parsetask')),
            ],
            options={
                'db_table': 'parse_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('cian', 'Циан'), ('avito', 'Авито'), ('yandex', 'Яндекс.Недвижимость')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('metro_station', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_owner', models.BooleanField(default=True)),
                ('no_commission', models.BooleanField(default=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('infrastructure', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apartments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='apartments_source_17df1f_idx'), models.Index(fields=['is_active', 'created_at'], name='apartments_is_acti_f3f62d_idx'), models.Index(fields=['price', 'area'], name='apartments_price_5affdc_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
